name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Set up Git repository
        continue-on-error: true
        uses: actions/checkout@v2
      - name: lualatex thesis
        continue-on-error: true
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
      - name: bibtex thesis
        continue-on-error: true
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.aux
          compiler: bibtex
          args: 
      - name: lualatex thesis
        continue-on-error: true
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
          compiler: lualatex
          args: -interaction=nonstopmode -shell-escape
